import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { styleContext } from "@/lib/ai/step2";
import { getResearch } from "@/lib/ai/research";
import { generateCreativePlatform, getPlatform } from "@/lib/ai/platform";
import { generateSketchBoard, type BoardSketch } from "@/lib/ai/sketch-board";
import { loadReferenceTaste } from "@/lib/ai/reference-taste";
import { hasTokens, spendTokens, TOKEN_COST } from "@/lib/credits";
import { chosenBrandName } from "@/lib/brands";
import { startClock } from "@/lib/ai/budget";
import { planBoard, BOARD_SIZE } from "@/lib/logo-board";
import { normalizeMarkTypes, normalizeStandaloneStyles } from "@/lib/logo-styles";

export const runtime = "nodejs";
export const maxDuration = 300;

// POST /api/generate/logo/board — the standalone logo flow's divergence step.
//
// One press draws a whole board: nine pencil croquis distributed across the
// (style world × mark type) pairings the client chose, never blended into
// hybrids. One design call writes all nine; nine renders run in parallel.
//
// Body: { brandId, config: { mark_types, standalone_styles, instructions },
//         reset?: boolean }
//
// Presses APPEND. A board grows until the client asks to start over, so a
// second press is nine more directions to compare against the first rather
// than a replacement for it.
export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  const body = (await request.json().catch(() => ({}))) as {
    brandId?: unknown;
    config?: unknown;
    reset?: unknown;
  };
  const brandId = typeof body.brandId === "string" ? body.brandId : "";
  if (!brandId) {
    return NextResponse.json({ error: "Missing brandId." }, { status: 400 });
  }
  const reset = body.reset === true;

  const rawConfig = (body.config ?? {}) as Record<string, unknown>;
  const markTypes = normalizeMarkTypes(rawConfig.mark_types);
  const standaloneStyles = normalizeStandaloneStyles(rawConfig.standalone_styles);
  const instructions =
    typeof rawConfig.instructions === "string"
      ? rawConfig.instructions.trim().slice(0, 1000)
      : "";

  if (!markTypes.length) {
    return NextResponse.json(
      { error: "Choose a logo type before sketching concepts." },
      { status: 400 },
    );
  }

  const { data: brand, error: loadError } = await supabase
    .from("brands")
    .select("id, brief, audience, competitors, name, name_choice, style_id, data")
    .eq("id", brandId)
    .maybeSingle();

  if (loadError) {
    return NextResponse.json({ error: loadError.message }, { status: 500 });
  }
  if (!brand) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
  if (!String(brand.brief ?? "").trim()) {
    return NextResponse.json(
      { error: "Add a brief before sketching logo concepts." },
      { status: 400 },
    );
  }

  if (!(await hasTokens(user.id, TOKEN_COST.asset))) {
    return NextResponse.json(
      { error: "You're out of tokens. Top up in Settings → Billing.", code: "no_tokens" },
      { status: 402 },
    );
  }

  const data = (brand.data as Record<string, unknown>) ?? {};
  const brandName = chosenBrandName(brand);
  const clock = startClock("logo/board", 280_000);

  try {
    // Research is generated by /logo/research, which the client calls first.
    // It is an aid rather than a prerequisite, so a board is still drawn
    // without it — but it is never generated here, because nine renders need
    // every second of the budget this route has.
    const research = getResearch(data);
    const ctx = styleContext(brand);

    let platform = getPlatform(data);
    if (!platform) {
      clock.guard("write the creative platform", 60_000);
      platform = await generateCreativePlatform({
        brief: String(brand.brief),
        name: brandName,
        audience: brand.audience as string | null,
        competitors: brand.competitors as string | null,
        styleContext: ctx,
      });
      clock.lap("platform");
    }

    const prior = reset ? [] : ((data.logo_board as BoardSketch[] | undefined) ?? []);
    const priorLikes = reset ? [] : ((data.logo_board_likes as string[] | undefined) ?? []);

    const referenceTaste = await loadReferenceTaste(supabase, data);
    const slots = planBoard(standaloneStyles, markTypes, BOARD_SIZE);

    clock.guard("draw the board", 200_000);
    const drawn = await generateSketchBoard({
      brandId,
      brief: String(brand.brief),
      name: brandName,
      platform,
      slots,
      styleContext: ctx,
      instructions: instructions || null,
      nameMeaning:
        typeof data.logo_name_meaning === "string" ? data.logo_name_meaning : null,
      referenceTaste,
      // Names already on the board, so a second press explores rather than
      // redraws what the client has already seen.
      avoidNames: prior.map((s) => s.name),
      clock,
    });

    await spendTokens(user.id, TOKEN_COST.asset);

    const board = [...prior, ...drawn];
    const nextData = {
      ...data,
      creative_platform: platform,
      logo_board: board,
      logo_board_likes: priorLikes,
      logo_board_config: {
        mark_types: markTypes,
        standalone_styles: standaloneStyles,
        instructions: instructions || null,
      },
    };
    const { error: saveError } = await supabase
      .from("brands")
      .update({ data: nextData })
      .eq("id", brandId);
    if (saveError) {
      console.error("Failed to save the sketch board:", saveError.message);
    }

    return NextResponse.json({
      platform,
      board,
      drawn: drawn.length,
      requested: slots.length,
      research,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Sketching the board failed.";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
