// Compiles skills/*/SKILL.md into src/lib/skills/generated.ts.
//
// The skills have to be readable from a route handler on Vercel. Serverless
// bundles only include files the build can see statically, so reading
// `skills/${name}/SKILL.md` at runtime — a path that only exists once a
// request names a skill — gets the file left out of the bundle and fails in
// production while working perfectly in dev. Generating a module removes the
// filesystem from the question entirely.
//
//   node scripts/build-skills.mjs           # write the module
//   node scripts/build-skills.mjs --check   # fail if it would change
//
// The frontmatter rules mirror upstream's validate-skills.sh: `name` must be
// 1–64 chars of lowercase alphanumerics and hyphens and match the directory,
// `description` must be 1–1024 chars.

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(root, "skills");
const OUT = join(root, "src", "lib", "skills", "generated.ts");

const NAME_RE = /^[a-z0-9-]{1,64}$/;

// Enough YAML for the frontmatter this spec allows: `key: value`, block
// scalars (`description: >`), and a one-level `metadata:` map. Deliberately
// not a YAML parser — an upstream file that needs more than this should fail
// loudly here rather than be silently half-read.
function parseFrontmatter(text, file) {
  if (!text.startsWith("---\n")) throw new Error(`${file}: no YAML frontmatter`);
  const end = text.indexOf("\n---", 4);
  if (end === -1) throw new Error(`${file}: unterminated frontmatter`);

  const head = text.slice(4, end);
  const body = text.slice(text.indexOf("\n", end + 1) + 1);

  const out = {};
  const lines = head.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim() || line.startsWith("#")) continue;
    const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const [, key, rawValue] = m;
    let value = rawValue.trim();

    // Block scalar: fold the indented continuation lines that follow.
    if (value === ">" || value === "|" || value === ">-" || value === "|-") {
      const folded = [];
      while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) {
        folded.push(lines[++i].trim());
      }
      value = folded.join(value.startsWith(">") ? " " : "\n");
    } else if (value === "") {
      // A nested map (`metadata:`) — skip its indented children; nothing below
      // reads them, and pretending to parse them would be worse than not.
      while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) i++;
      continue;
    }

    value = value.replace(/^["'](.*)["']$/s, "$1");
    out[key] = value;
  }

  if (!out.name) throw new Error(`${file}: missing 'name'`);
  if (!NAME_RE.test(out.name)) throw new Error(`${file}: invalid 'name' — ${out.name}`);
  if (!out.description) throw new Error(`${file}: missing 'description'`);
  if (out.description.length > 1024) {
    throw new Error(`${file}: 'description' is ${out.description.length} chars, max 1024`);
  }
  if (!body.trim()) throw new Error(`${file}: empty body`);

  return { name: out.name, description: out.description, body: body.trim() };
}

function collect() {
  const dirs = readdirSync(SKILLS_DIR)
    .filter((entry) => statSync(join(SKILLS_DIR, entry)).isDirectory())
    .sort();

  return dirs.map((dir) => {
    const file = join("skills", dir, "SKILL.md");
    const skill = parseFrontmatter(readFileSync(join(root, file), "utf8"), file);
    if (skill.name !== dir) {
      throw new Error(`${file}: name '${skill.name}' does not match directory '${dir}'`);
    }
    return skill;
  });
}

function render(skills) {
  const entries = skills
    .map(
      (s) =>
        `  ${JSON.stringify(s.name)}: {\n` +
        `    name: ${JSON.stringify(s.name)},\n` +
        `    description: ${JSON.stringify(s.description)},\n` +
        `    body: ${JSON.stringify(s.body)},\n` +
        `  },`,
    )
    .join("\n");

  return `// GENERATED by scripts/build-skills.mjs — do not edit.
// Source: skills/*/SKILL.md (vendored, MIT — see skills/README.md).
// Regenerate with \`npm run skills:build\`; CI enforces it with \`skills:check\`.

export interface Skill {
  /** Directory name and stable id, e.g. "brand-naming". */
  name: string;
  /** Upstream's trigger description. Not shown to users. */
  description: string;
  /** The instruction body, frontmatter stripped. */
  body: string;
}

export const SKILLS: Record<string, Skill> = {
${entries}
};
`;
}

const skills = collect();
const next = render(skills);

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error("src/lib/skills/generated.ts is missing. Run `npm run skills:build`.");
    process.exit(1);
  }
  if (current !== next) {
    console.error(
      "src/lib/skills/generated.ts is out of date with skills/*/SKILL.md.\n" +
        "Run `npm run skills:build` and commit the result.",
    );
    process.exit(1);
  }
  console.log(`skills: ${skills.length} skills, generated module up to date`);
} else {
  writeFileSync(OUT, next);
  console.log(`skills: wrote ${skills.length} skills to src/lib/skills/generated.ts`);
}
